### ISSUE TITLE
运行demo时，总是会遇到Attribute ":visible.sync" is ignored on component 

### ISSUE THREAD

**Issue by wxytjustb** [ElemeFE/vue-popup#4]
按照文档上的代码，运行时，总是出现以下代码
Vue warn]: Attribute ":visible.sync" is ignored on component <alert> because the component is a fragment instance

把alert中的v-if="rendered"去掉就没有这个提示，请问是什么原因呢，谢谢了

**Comment by Leopoldthecoder** [comment]
是有这个问题，如果 `rendered` 为 `false` 的话会被认为是 fragment instance，所以不建议在使用 vue-popup 的组件上写 `v-if="rendered"`。抱歉例子没有及时更新，我去改一下。

**Comment by wxytjustb** [comment]
哇，回复的这么迅速，非常感谢。
接着说问题，我不用npm install的vue-popup，而直接使用源码就没有这个问题了。
将代码
import Popup from 'vue-popup'
改成
import Popup from './src/index'
就可以了

请问这是什么原因呢？

**Comment by Leopoldthecoder** [comment]
我有空看看，先存疑
